[package]
name = "tycho2_renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
csv = "1.3.0"
image = "0.25.2"
nalgebra = "0.33.0"
serde = { version = "1.0.209", features = ["derive"] }
spec_math = "0.1.5"
thiserror = "1.0.63"
